import "@ddcore/sdk/test";
import { generate } from "./demo";

// The test database may already have run `ddcore demo`; each `it` runs in a
// rolled-back transaction, so cleaning up here affects no other test and no row.
const DEMO_PROJECTS = ["DEMO", "PORTAL", "INFRA"];
const DEMO_USERS = ["ana@example.com", "carlos@example.com", "beatriz@example.com"];

function clearDemo() {
  for (const p of DEMO_PROJECTS) {
    for (const t of ddcore.db.getAll<{ name: string }>("Task", { filters: { project: p }, fields: ["name"] })) {
      ddcore.deleteDoc("Task", t.name, { force: true });
    }
    if (ddcore.db.exists("Project", p)) ddcore.deleteDoc("Project", p, { force: true });
  }
  for (const email of DEMO_USERS) {
    if (ddcore.db.exists("User", email)) ddcore.deleteDoc("User", email, { force: true });
  }
  for (const td of ddcore.db.getAll<{ name: string }>("ToDo", { fields: ["name"] })) {
    ddcore.deleteDoc("ToDo", td.name, { force: true });
  }
}

describe("demo", () => {
  beforeEach(clearDemo);

  it("creates demo users, projects, tasks, and todos", () => {
    const r = generate();

    // Users
    for (const email of DEMO_USERS) {
      expect(r.created).toContain(email);
      expect(ddcore.db.exists("User", email)).toBe(email);
      expect(ddcore.db.getValue<boolean>("User", email, "enabled")).toBe(true);
    }

    // Projects
    for (const p of DEMO_PROJECTS) {
      expect(r.created).toContain(p);
      expect(ddcore.db.exists("Project", p)).toBe(p);
    }

    // Milestones
    expect(ddcore.db.count("Project Milestone", { parent: "DEMO" })).toBe(3);
    expect(ddcore.db.count("Project Milestone", { parent: "PORTAL" })).toBe(3);
    expect(ddcore.db.count("Project Milestone", { parent: "INFRA" })).toBe(3);

    // Tasks
    expect(r.created).toContain("DEMO-01");
    expect(r.created).toContain("PORT-01");
    expect(r.created).toContain("INF-01");

    expect(ddcore.db.getValue("Task", "DEMO-01", "status")).toBe("Open");
    expect(ddcore.db.getValue("Task", "DEMO-02", "status")).toBe("In progress");
    expect(ddcore.db.getValue("Task", "DEMO-03", "status")).toBe("Completed");
    expect(ddcore.db.getValue("Task", "PORT-02", "status")).toBe("Completed");

    // ToDos
    expect(ddcore.db.count("ToDo")).toBeGreaterThanOrEqual(4);
    expect(ddcore.db.count("ToDo", { allocated_to: "ana@example.com" })).toBeGreaterThanOrEqual(1);
    expect(ddcore.db.count("ToDo", { allocated_to: "carlos@example.com" })).toBeGreaterThanOrEqual(1);

    // Notifications generated by rules
    const notifications = ddcore.db.sql<{ count: number }>("SELECT count(*)::int AS count FROM ddcore_notification");
    expect(notifications[0].count).toBeGreaterThanOrEqual(3);

    expect(r.count).toBe(r.created.length);
  });

  it("a second run duplicates nothing", () => {
    generate();
    const r = generate();
    expect(r.count).toBe(0);
    expect(r.created).toHaveLength(0);

    expect(ddcore.db.count("Project", { code: "DEMO" })).toBe(1);
    expect(ddcore.db.count("Project", { code: "PORTAL" })).toBe(1);
    expect(ddcore.db.count("Project", { code: "INFRA" })).toBe(1);

    for (const email of DEMO_USERS) {
      expect(ddcore.db.count("User", { email })).toBe(1);
    }
  });
});

